#!/bin/bash

INSTALL_PATH="$(dirname "${BASH_SOURCE[0]}")/target"
IFS="="
PARAMS=""
while read -r key value
do
        PARAMS="$PARAMS -D$key=$value"
done < "$1"
eval "java$PARAMS -jar $INSTALL_PATH/catmaid-tile.jar"
#java$PARAMS -jar $INSTALL_PATH/catmaid-tile.jar
